"""tabelas admin

Revision ID: 5f2101ec027b
Revises: 
Create Date: 2019-03-10 19:19:55.385173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2101ec027b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(length=30), nullable=False),
    sa.Column('Sobrenome', sa.String(length=60), nullable=False),
    sa.Column('Data de Nascimento', sa.Date(), nullable=False),
    sa.Column('CPF', sa.Integer(), nullable=False),
    sa.Column('Telefone', sa.Integer(), nullable=False),
    sa.Column('E-Mail', sa.String(length=70), nullable=False),
    sa.Column('CEP', sa.Integer(), nullable=False),
    sa.Column('Rua', sa.String(length=90), nullable=False),
    sa.Column('Número', sa.Integer(), nullable=False),
    sa.Column('Complemento', sa.String(length=50), nullable=True),
    sa.Column('Bairro', sa.String(length=50), nullable=False),
    sa.Column('Cidade', sa.String(length=80), nullable=False),
    sa.Column('Observações', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(length=50), nullable=False),
    sa.Column('Tipo', sa.String(length=30), nullable=False),
    sa.Column('Quantidade', sa.Integer(), nullable=False),
    sa.Column('Descrição', sa.String(length=500), nullable=True),
    sa.Column('Código', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('Data do Pedido', sa.Date(), nullable=True),
    sa.Column('Data que foi feito', sa.Date(), nullable=True),
    sa.Column('Data que foi cancelado', sa.Date(), nullable=True),
    sa.Column('Motivo cancelamento', sa.String(length=200), nullable=True),
    sa.Column('PDF link e/ou nome', sa.String(length=200), nullable=True),
    sa.Column('clienteId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clienteId'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orcamentos')
    op.drop_table('estoque')
    op.drop_table('cliente')
    # ### end Alembic commands ###
